### ISSUE TITLE
[Step 6] CMD 'arm-none-eabi-gcc' doesn't work, but 'gcc' does

### ISSUE THREAD

**Issue by human890209** [TamojitSaha/Compiling_Arduino_STM32_bootloaders#1]
Hi,
I'm following your steps, cause I'm using Windows, too. (win10 x64)
[Step6]  I enter 'arm-none-eabi-gcc' in CMD, but it's not recognized.
Then I tried entering 'gcc', it worked.
I only found gcc.exe in the bin folder.
-----
Than I found there are arm-none-eabi-gcc.exe in the bin folder:
C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\bin
So if I want to use  'arm-none-eabi-gcc'  in cmd, I should add
"C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\bin"
but not
"C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\arm-none-eabi\bin"

I don't know if it's your typo or my mistake. I'm a newbie of cmd.
I'm confusing now, which bin should I add, I'm going to test it myself.

**Comment by TamojitSaha** [comment]
Hello,
Glad to see that someone is interested in compiling the bootloader.
Regarding your doubt, as mentioned in [STEP 5](https://github.com/TamojitSaha/Compiling_Arduino_STM32_bootloaders/blob/master/README.md#step_5) the directory to add in **PATH** variable should look like `C:\your_installation_directory\GNU Tools ARM Embedded\4.8.3-2014q1\arm-none-eabi\bin`
You should add this directory to both *System Variables* and *User Variables*.
If still problem persists please comment.

**Comment by human890209** [comment]
Hi, I did put the [GNU Tools ARM Embedded] folder under my [C:\Program Files (x86)]
I added,
C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\bin
to succeed in [Step 6] which run "arm-none-eabi-gcc"
if I only add
C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\arm-none-eabi\bin
I succeed to run "gcc" but "arm-none-eabi-gcc" failed, because [arm-none-eabi-gcc.exe] is not there.

And I also add it in case the [make] needs it (I don't know)
And I succeed in building the bin file of the bootloader.

I keep both, I really stuck in [Step6] for a while. 
You can check where the [arm-none-eabi-gcc.exe] is. The files I use are all from your links.

Thanks anyway. Without your indication, I can't use my none-generic board. Thank you very much!

**Comment by TamojitSaha** [comment]
I just checked the ARM-GNU Toolchain files.
The proper directory to be added in **PATH** should look like: `C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\bin` as you said. I will make a correction in the **STEPS**. Thanks for notifying the mistake! :smile: :wink: 

> @human890209 
 And I also add it in case the [make] needs it (I don't know)

Kindly can you be more specific? Didn't understand.

>@human890209  
And I succeed in building the bin file of the bootloader.

Congratulations on that!! :+1: :smiley: 

> @human890209 
Thanks anyway. Without your indication, I can't use my none-generic board. Thank you very much!

As you mentioned above you were able to compile the bootloader then what are the difficulties you are facing?? Please comment in details with proper markdown formatting. It would then help me to debug your issues.

**Comment by human890209** [comment]
Hi,
And I also add it in case the [make] needs it (I don't know).
Cause I don't know if the STEP6 is wrong or the STEP5 is wrong, so I add both paths.
I post this issue to remind there must be one mistake in STEP5/ STEP6.
Now I know
C:\Program Files (x86)\GNU Tools ARM Embedded\4.8.3-2014q1\bin
is the one that needed.

Thanks.
I think the issue is closed.

**Comment by SandeepanSengupta** [comment]
Hi @human890209, may I know any details regarding your use of this bootloader ?
I'm interested in making a dev board.

**Comment by human890209** [comment]
Hi, @SandeepanSengupta ,
I just follow the roger bootloader's instructions and TamojitSaha's instructions.
I'm not an expert, just follow every step and test.

**Comment by TamojitSaha** [comment]
I am glad that it helped you in compiling the bootloader from scratch. :beers: to that! You can even rename the board description, if you want. Like instead of *Maple Mini* you can alter the name of your board. But for that you have to modify the drivers for it. :wink:
